spring.application.name=main
spring.data.redis.host = localhost
spring.data.redis.port = 6379
server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=backend-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/backend/**